import { Entry } from "./types";

export const ENTRIES: Entry[] = [
  {
    id: "entry-1",
    name: "James T",
    owner: "James T",
    golfers: [
      "Ludvig Aberg",
      "Chris Gotterup",
      "Akshay Bhatia",
      "Sepp Straka",
      "Marco Penge",
      "Aaron Rai",
      "Haotong Li",
      "Sami Valimaki",
    ],
    tiebreakerGuess: 1053,
  },
  {
    id: "entry-2",
    name: "Daniel T",
    owner: "Daniel T",
    golfers: [
      "Scottie Scheffler",
      "Collin Morikawa",
      "Shane Lowry",
      "Daniel Berger",
      "Sung-Jae Im",
      "Brian Harman",
      "Andrew Novak",
      "Davis Riley",
    ],
    tiebreakerGuess: 842,
  },
  {
    id: "entry-3",
    name: "Pat O",
    owner: "Pat O",
    golfers: [
      "Cameron Young",
      "Robert MacIntyre",
      "Akshay Bhatia",
      "Tyrrell Hatton",
      "Sung-Jae Im",
      "Nick Taylor",
      "Tom McKibbin",
      "Michael Brennan",
    ],
    tiebreakerGuess: 801,
  },
  {
    id: "entry-4",
    name: "Matty T",
    owner: "Matty T",
    golfers: [
      "Scottie Scheffler",
      "Brooks Koepka",
      "Justin Thomas",
      "Tyrrell Hatton",
      "Cameron Smith",
      "Brian Harman",
      "Nico Echavarria",
      "Bubba Watson",
    ],
    tiebreakerGuess: 830,
  },
  {
    id: "entry-5",
    name: "Clay B",
    owner: "Clay B",
    golfers: [
      "Ludvig Aberg",
      "Robert MacIntyre",
      "Akshay Bhatia",
      "Sepp Straka",
      "Max Homa",
      "Nick Taylor",
      "Dustin Johnson",
      "John Keefer",
    ],
    tiebreakerGuess: 950,
  },
  {
    id: "entry-6",
    name: "Eric S",
    owner: "Eric S",
    golfers: [
      "Ludvig Aberg",
      "Justin Rose",
      "Si Woo Kim",
      "Harris English",
      "Sung-Jae Im",
      "Michael Kim",
      "Haotong Li",
      "Davis Riley",
    ],
    tiebreakerGuess: 963,
  },
  {
    id: "entry-7",
    name: "Gabe K",
    owner: "Gabe K",
    golfers: [
      "Ludvig Aberg",
      "Min Woo Lee",
      "Akshay Bhatia",
      "Nicolai Hojgaard",
      "Cameron Smith",
      "Sam Stevens",
      "Carlos Ortiz",
      "Michael Brennan",
    ],
    tiebreakerGuess: 973,
  },
  {
    id: "entry-8",
    name: "Mike R",
    owner: "Mike R",
    golfers: [
      "Tommy Fleetwood",
      "Brooks Koepka",
      "Shane Lowry",
      "Gary Woodland",
      "Max Homa",
      "Nick Taylor",
      "Dustin Johnson",
      "Bubba Watson",
    ],
    tiebreakerGuess: 735,
  },
  {
    id: "entry-9",
    name: "Quin S",
    owner: "Quin S",
    golfers: [
      "Jon Rahm",
      "Collin Morikawa",
      "Jason Day",
      "Corey Conners",
      "Sung-Jae Im",
      "Wyndham Clark",
      "Andrew Novak",
      "Zach Johnson",
    ],
    tiebreakerGuess: 879,
  },
  {
    id: "entry-10",
    name: "Andrew S",
    owner: "Andrew S",
    golfers: [
      "Scottie Scheffler",
      "Chris Gotterup",
      "Akshay Bhatia",
      "Sepp Straka",
      "Sung-Jae Im",
      "Nick Taylor",
      "Casey Jarvis",
      "Zach Johnson",
    ],
    tiebreakerGuess: 913,
  },
  {
    id: "entry-11",
    name: "Ari G",
    owner: "Ari G",
    golfers: [
      "Bryson DeChambeau",
      "Patrick Reed",
      "Patrick Cantlay",
      "Nicolai Hojgaard",
      "Max Homa",
      "Ryan Fox",
      "Aldrich Potgieter",
      "Sami Valimaki",
    ],
    tiebreakerGuess: 847,
  },
  {
    id: "entry-12",
    name: "Brent W",
    owner: "Brent W",
    golfers: [
      "Xander Schauffele",
      "Viktor Hovland",
      "Jason Day",
      "Tyrrell Hatton",
      "Keegan Bradley",
      "Ryan Fox",
      "Dustin Johnson",
      "Danny Willett",
    ],
    tiebreakerGuess: 888,
  },
  {
    id: "entry-13",
    name: "JT P",
    owner: "JT P",
    golfers: [
      "Scottie Scheffler",
      "Collin Morikawa",
      "Akshay Bhatia",
      "Nicolai Hojgaard",
      "Ben Griffin",
      "Wyndham Clark",
      "Carlos Ortiz",
      "Sami Valimaki",
    ],
    tiebreakerGuess: 810,
  },
  {
    id: "entry-14",
    name: "Eric T",
    owner: "Eric T",
    golfers: [
      "Bryson DeChambeau",
      "Jordan Spieth",
      "Justin Thomas",
      "Corey Conners",
      "Ben Griffin",
      "Brian Harman",
      "Carlos Ortiz",
      "Michael Brennan",
    ],
    tiebreakerGuess: 910,
  },
  {
    id: "entry-15",
    name: "Matt E",
    owner: "Matt E",
    golfers: [
      "Jon Rahm",
      "Viktor Hovland",
      "Akshay Bhatia",
      "Corey Conners",
      "Max Homa",
      "Brian Harman",
      "Dustin Johnson",
      "Danny Willett",
    ],
    tiebreakerGuess: 875,
  },
  {
    id: "entry-16",
    name: "Andrew B",
    owner: "Andrew B",
    golfers: [
      "Jon Rahm",
      "Justin Rose",
      "Akshay Bhatia",
      "Corey Conners",
      "Rasmus Hojgaard",
      "Sam Stevens",
      "Matt McCarty",
      "John Keefer",
    ],
    tiebreakerGuess: 978,
  },
  {
    id: "entry-17",
    name: "Austin O",
    owner: "Austin O",
    golfers: [
      "Scottie Scheffler",
      "Justin Rose",
      "Jake Knapp",
      "Sepp Straka",
      "Cameron Smith",
      "Wyndham Clark",
      "Dustin Johnson",
      "Davis Riley",
    ],
    tiebreakerGuess: 999,
  },
  {
    id: "entry-18",
    name: "Tommy C",
    owner: "Tommy C",
    golfers: [
      "Bryson DeChambeau",
      "Min Woo Lee",
      "Akshay Bhatia",
      "Harris English",
      "Sung-Jae Im",
      "Sam Stevens",
      "Rasmus Neergaard",
      "Sami Valimaki",
    ],
    tiebreakerGuess: 962,
  },
  {
    id: "entry-19",
    name: "Ian L",
    owner: "Ian L",
    golfers: [
      "Scottie Scheffler",
      "Patrick Reed",
      "JJ Spaun",
      "Harris English",
      "Sung-Jae Im",
      "Ryan Fox",
      "Matt McCarty",
      "Zach Johnson",
    ],
    tiebreakerGuess: 945,
  },
];

// Name aliases: entry name -> ESPN's athlete.fullName
export const NAME_ALIASES: Record<string, string> = {
  "Ludvig Aberg": "Ludvig Åberg",
  "Nicolai Hojgaard": "Nicolai Højgaard",
  "Rasmus Hojgaard": "Rasmus Højgaard",
  "Sami Valimaki": "Sami Välimäki",
  "Sung-Jae Im": "Sungjae Im",
  "JJ Spaun": "J.J. Spaun",
  "John Keefer": "Johnny Keefer",
  "Rasmus Neergaard": "Rasmus Neergaard-Petersen",
};

export function resolveGolferName(name: string): string {
  return NAME_ALIASES[name] || name;
}
