import { Entry } from "../types";

export const PGA_ENTRIES: Entry[] = [
  {
    id: "pga-1",
    name: "James T",
    owner: "James T",
    golfers: [
      "Scottie Scheffler",
      "Tommy Fleetwood",
      "Sam Burns",
      "J.J. Spaun",
      "Gary Woodland",
      "Jason Day",
      "Sungjae Im",
      "Pierceson Coody",
    ],
    tiebreakerGuess: 1453,
  },
  {
    id: "pga-2",
    name: "Ari G",
    owner: "Ari G",
    golfers: [
      "Matt Fitzpatrick",
      "Collin Morikawa",
      "Si Woo Kim",
      "Akshay Bhatia",
      "Shane Lowry",
      "Keegan Bradley",
      "Wyndham Clark",
      "Ryan Gerard",
    ],
    tiebreakerGuess: 1111,
  },
  {
    id: "pga-3",
    name: "Eric T",
    owner: "Eric T",
    golfers: [
      "Scottie Scheffler",
      "Tommy Fleetwood",
      "Rickie Fowler",
      "Min Woo Lee",
      "Shane Lowry",
      "Alex Smalley",
      "Sahith Theegala",
      "Matt McCarty",
    ],
    tiebreakerGuess: 869,
  },
  {
    id: "pga-4",
    name: "Matty T",
    owner: "Matty T",
    golfers: [
      "Scottie Scheffler",
      "Patrick Cantlay",
      "Nicolai Hojgaard",
      "J.J. Spaun",
      "Harris English",
      "Thomas Detry",
      "Alex Noren",
      "Matt McCarty",
    ],
    tiebreakerGuess: 787,
  },
  {
    id: "pga-5",
    name: "Daniel T",
    owner: "Daniel T",
    golfers: [
      "Rory McIlroy",
      "Justin Rose",
      "Viktor Hovland",
      "Akshay Bhatia",
      "Shane Lowry",
      "Thomas Detry",
      "Wyndham Clark",
      "Daniel Berger",
    ],
    tiebreakerGuess: 1492,
  },
  {
    id: "pga-6",
    name: "Matt E",
    owner: "Matt E",
    golfers: [
      "Xander Schauffele",
      "Tommy Fleetwood",
      "Viktor Hovland",
      "Akshay Bhatia",
      "Harris English",
      "Jason Day",
      "Sahith Theegala",
      "Daniel Berger",
    ],
    tiebreakerGuess: 1479,
  },
  {
    id: "pga-7",
    name: "Andrew S",
    owner: "Andrew S",
    golfers: [
      "Scottie Scheffler",
      "Tommy Fleetwood",
      "Tyrell Hatton",
      "J.J. Spaun",
      "Shane Lowry",
      "Alex Fitzpatrick",
      "Corey Conners",
      "Daniel Berger",
    ],
    tiebreakerGuess: 2233,
  },
  {
    id: "pga-8",
    name: "Eric S",
    owner: "Eric S",
    golfers: [
      "Cameron Young",
      "Justin Thomas",
      "Rickie Fowler",
      "Hideki Matsuyama",
      "Gary Woodland",
      "Jason Day",
      "Sahith Theegala",
      "Daniel Berger",
    ],
    tiebreakerGuess: 666,
  },
  {
    id: "pga-9",
    name: "Brent W",
    owner: "Brent W",
    golfers: [
      "Scottie Scheffler",
      "Tommy Fleetwood",
      "Viktor Hovland",
      "Hideki Matsuyama",
      "Shane Lowry",
      "Jason Day",
      "Corey Conners",
      "Daniel Berger",
    ],
    tiebreakerGuess: 888,
  },
];
