export const MOCK_PGA_DRAFT = {
  tournament_id: "pga",
  name: "2026 Juice Championship Draft",
  tiers: [
    { tier_number: 1, name: "Tier 1 — Elite" },
    { tier_number: 2, name: "Tier 2 — Contenders" },
    { tier_number: 3, name: "Tier 3 — Threats" },
    { tier_number: 4, name: "Tier 4 — Solid" },
    { tier_number: 5, name: "Tier 5 — Sleepers" },
    { tier_number: 6, name: "Tier 6 — Mid-Range" },
    { tier_number: 7, name: "Tier 7 — Longshots" },
    { tier_number: 8, name: "Tier 8 — Dark Horses" },
  ],
  golfers: [
    // Tier 1
    { tier_number: 1, name: "Scottie Scheffler" },
    { tier_number: 1, name: "Xander Schauffele" },
    { tier_number: 1, name: "Rory McIlroy" },
    { tier_number: 1, name: "Jon Rahm" },
    { tier_number: 1, name: "Collin Morikawa" },
    { tier_number: 1, name: "Bryson DeChambeau" },
    { tier_number: 1, name: "Ludvig Aberg" },
    { tier_number: 1, name: "Tommy Fleetwood" },
    { tier_number: 1, name: "Wyndham Clark" },
    { tier_number: 1, name: "Cameron Young" },
    // Tier 2
    { tier_number: 2, name: "Brooks Koepka" },
    { tier_number: 2, name: "Viktor Hovland" },
    { tier_number: 2, name: "Jordan Spieth" },
    { tier_number: 2, name: "Patrick Cantlay" },
    { tier_number: 2, name: "Justin Thomas" },
    { tier_number: 2, name: "Robert MacIntyre" },
    { tier_number: 2, name: "Shane Lowry" },
    { tier_number: 2, name: "Min Woo Lee" },
    { tier_number: 2, name: "Chris Gotterup" },
    { tier_number: 2, name: "Justin Rose" },
    // Tier 3
    { tier_number: 3, name: "Akshay Bhatia" },
    { tier_number: 3, name: "Patrick Reed" },
    { tier_number: 3, name: "Jason Day" },
    { tier_number: 3, name: "Si Woo Kim" },
    { tier_number: 3, name: "Jake Knapp" },
    { tier_number: 3, name: "Tony Finau" },
    { tier_number: 3, name: "Sam Burns" },
    { tier_number: 3, name: "Hideki Matsuyama" },
    { tier_number: 3, name: "Sahith Theegala" },
    { tier_number: 3, name: "Russell Henley" },
    // Tier 4
    { tier_number: 4, name: "Tyrrell Hatton" },
    { tier_number: 4, name: "Corey Conners" },
    { tier_number: 4, name: "Nicolai Hojgaard" },
    { tier_number: 4, name: "Sepp Straka" },
    { tier_number: 4, name: "Harris English" },
    { tier_number: 4, name: "Daniel Berger" },
    { tier_number: 4, name: "Gary Woodland" },
    { tier_number: 4, name: "Adam Scott" },
    { tier_number: 4, name: "Keegan Bradley" },
    { tier_number: 4, name: "Denny McCarthy" },
    // Tier 5
    { tier_number: 5, name: "Max Homa" },
    { tier_number: 5, name: "Cameron Smith" },
    { tier_number: 5, name: "Ben Griffin" },
    { tier_number: 5, name: "Sung-Jae Im" },
    { tier_number: 5, name: "Rasmus Hojgaard" },
    { tier_number: 5, name: "Keegan Bradley" },
    { tier_number: 5, name: "Cameron Davis" },
    { tier_number: 5, name: "Adam Hadwin" },
    { tier_number: 5, name: "Taylor Moore" },
    { tier_number: 5, name: "J.T. Poston" },
    // Tier 6
    { tier_number: 6, name: "Nick Taylor" },
    { tier_number: 6, name: "Brian Harman" },
    { tier_number: 6, name: "Aaron Rai" },
    { tier_number: 6, name: "Ryan Fox" },
    { tier_number: 6, name: "Sam Stevens" },
    { tier_number: 6, name: "Wyndham Clark" },
    { tier_number: 6, name: "Michael Kim" },
    { tier_number: 6, name: "Thomas Detry" },
    { tier_number: 6, name: "Kurt Kitayama" },
    { tier_number: 6, name: "Lee Hodges" },
    // Tier 7
    { tier_number: 7, name: "Dustin Johnson" },
    { tier_number: 7, name: "Carlos Ortiz" },
    { tier_number: 7, name: "Andrew Novak" },
    { tier_number: 7, name: "Matt McCarty" },
    { tier_number: 7, name: "Haotong Li" },
    { tier_number: 7, name: "Tom McKibbin" },
    { tier_number: 7, name: "Aldrich Potgieter" },
    { tier_number: 7, name: "Nico Echavarria" },
    { tier_number: 7, name: "Casey Jarvis" },
    { tier_number: 7, name: "Mac Meissner" },
    // Tier 8
    { tier_number: 8, name: "Bubba Watson" },
    { tier_number: 8, name: "Danny Willett" },
    { tier_number: 8, name: "Sami Valimaki" },
    { tier_number: 8, name: "Davis Riley" },
    { tier_number: 8, name: "Michael Brennan" },
    { tier_number: 8, name: "John Keefer" },
    { tier_number: 8, name: "Zach Johnson" },
    { tier_number: 8, name: "Marco Penge" },
    { tier_number: 8, name: "Rasmus Neergaard" },
    { tier_number: 8, name: "Chris Kirk" },
  ],
  members: [
    "James T", "Daniel T", "Pat O", "Matty T", "Clay B",
    "Eric S", "Gabe K", "Mike R", "Quin S", "Andrew S",
    "Ari G", "Brent W", "JT P", "Eric T", "Matt E",
    "Andrew B", "Austin O", "Tommy C", "Ian L",
  ],
};
